spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/calc_warehouse
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


server:
  port: 8084